version: "3.1"
services:
    buildXMLProvider:
        image: maven:3.6.0-jdk-11-slim
        command: 'mvn -f /home/app/pom.xml clean install'
        volumes:
            - "./XML-provider:/home/app"
    buildWebhookProvider:
        image: maven:3.6.0-jdk-11-slim
        command: 'mvn -f /home/app/pom.xml clean install'
        volumes:
            - "./webhook-provider:/home/app"
    buildTwofactorSMSAuthenticator:
        image: maven:3.6.0-jdk-11-slim
        command: 'mvn -f /home/app/pom.xml clean install'
        volumes:
            - "./twofactor-sms-authenticator:/home/app"
    buildProvisioningEventListener:
        image: maven:3.6.0-jdk-11-slim
        command: 'mvn -f /home/app/pom.xml clean install'
        volumes:
            - "./provisioning-event-listener:/home/app"