version: "3.1"
services:
    keycloak:
        depends_on:
            - keycloak-db
        ports:
            - "8080:8080"
        build: .
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
            KC_DB: mysql
            KC_DB_URL: jdbc:mysql://keycloak-db:3306/keycloak?useSSL=false&characterEncoding=UTF-8
            KC_DB_USERNAME: keycloak
            KC_DB_PASSWORD: password
        command:
            - "start-dev"
        volumes:
            - "./themes:/opt/keycloak/themes"
            - "./providers:/opt/keycloak/providers"
    keycloak-db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: keycloak
            MYSQL_USER: keycloak
            MYSQL_PASSWORD: password
networks:
    default:
        external:
            name: keycloak-network
