version: '2.1'
services:
    mysql:
        container_name: mysql
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: keycloak
            MYSQL_USER: keycloak
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root_password
    keycloak:
        container_name: keycloak
        image: quay.io/keycloak/keycloak:latest
        depends_on:
            - mysql
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
            KC_DB: mysql
            KC_DB_URL: jdbc:mysql://mysql:3306/keycloak
            KC_DB_USERNAME: keycloak
            KC_DB_PASSWORD: password
        command:
            - "start-dev"
networks:
    default:
        name: keycloak-network